### PR TITLE
fill in mentor assignment list for weeks 1-4 in London & week 1-2 in Nazareth

### PR DESCRIPTION
**Pull request by jsms90**
+ Create cross-campus mentor assignment list
+ Fill in London's assignments for weeks 1-3 (week 3 still a work in progress)
+ Fill in Nazareth's column for week 1

@Samatar26 @antoniotrkdz @oliverjam @finnhodgkin @mattlub @m4v15 - please confirm that these assignments were correct for your weeks

Week 3 in London is a work in progress. Will finish by the end of the day

relates #437

### CODE REVIEW

**Comment by jsms90** [comment]
@m4v15 I see that you've added part of the breakdown for Nazareth week 2. I've updated the title of this PR, if you could fill in the rest of the sections?

**Comment by mattlub** [comment]
@jsms90 thanks- sorry that was me, I thought you were asking us to fill it in, I didn't read it properly.

**Comment by rebeccaradding** [comment]
@majakudlicka thought you were in Nazareth week 5? And @yvonne-liu which weeks are you in Naz and Gaza now?

**Comment by yvonne-liu** [comment]
@rebeccaradding @jsms90 here is my mentoring schedule. It's the most updated schedule I have: 

July 17th - July 21st: London Week 4 with @ZooeyMiller 
July 24th - July 27th: Nazareth Week 4 with @ZooeyMiller and @finnhodgkin (I arrive a day later, so Zooey and Finn will do Day 1 of Week 4 without me) 
July 31 - August 4th: I will most likely still be around Nazareth, so I will help out with Nazareth Week 5 with @majakudlicka 
August 6th - August 10th: Gaza Week 5 with @eliascodes and @majakudlicka

**Comment by jsms90** [comment]
@rebeccaradding This PR only contains weeks 1-3 :confused: so you wouldn't see @yvonne-liu or @majakudlicka here anywhere

Haha, sorry @mattlub. Tagged the wrong Matt :wink: 
Don't apologise. Filling in week 2 is great! Just a few missing fields:
+ [ ] Which (if any) mentors have been around to support during the projects?
  + [ ] Week 1
  + [ ] Week 2
+ [ ] Who took minutes during the week 1 SGC?
+ [ ] Who introduced the todo app project?
+ [ ] What's the split like for today's tasks (Week 2 day 5)?

**Comment by m4v15** [comment]
I guess it works differently in Nazareth to London, but one of the lead mentors will always be involved in delivering the workshops, but we haven't explicitly assigned people for Week 3 yet, I'd say just assign the lead mentors for the week.

**Comment by mattlub** [comment]
> Which (if any) mentors have been around to support during the projects?

As mavis said, it's probably a bit more fluid here, there are a lot of us 'around'
> Week 1

Me, Mavis, Suha, Mario, Mohamed, Joudy
> Week 2

Reem, Mavis, me, Suha, Mario, Joudy, Mohamed
> Who took minutes during the week 1 SGC?

Me ([link](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/facn2/week1.md))
> Who introduced the todo app project?

I think Mavis, Reem (week leaders)
> What's the split like for today's tasks (Week 2 day 5)?

Mainly Reem + Mavis, while me, Suha, Mario, Mohamed, Joudy are pitching in

**Comment by jsms90** [comment]
@eliascodes @des-des Should I get the London mentors to merge this in or you guys?

**Comment by eliascodes** [comment]
Haven't been doing such granular task breakdowns in Gaza, but have added mentors for each week. If this is about tagging in PR's, just tag all (read: both) mentors responsible for the week.

**Pull request merged**
