### PR TITLE
Update Week 2 learning outcomes for FAC 11

### PR DESCRIPTION
**Pull request by oliverjam**
Add Tape, npm & callbacks.
Remove QUnit & waterfall as we are not teaching them this week.

Relates #329

### CODE REVIEW

**Comment by oliverjam** [comment]
I just noticed @jsms90's suggestions to make the learning outcomes more specific in #329, so I'll get that done before this can be merged.

**Comment by jsms90** [comment]
@oliverjam Thanks for the specificity! This is looking much better :dancer: 
Could you please reformulate the 3 sentences which are currently questions? Being very specific about _what_ we want students to understand about testing and about TDD as a methodology would be good :+1:

**Comment by oliverjam** [comment]
@jsms90 How's that?

**Comment by jsms90** [comment]
@oliverjam has anything changed? :confused:

**Comment by oliverjam** [comment]
@jsms90 Sorry the push failed at first for some reason. I blame the Wi-Fi...

**Comment by jsms90** [comment]
@oliverjam can you push up?

**Comment by oliverjam** [comment]
@jsms90 They should already be there. It went through right after I commented about the Wi-Fi

**Pull request merged**
