### PR TITLE
Update links to duplicated resources

### PR DESCRIPTION
**Pull request by astroash**
:godmode:

### CODE REVIEW

**Comment by eliascodes** [comment]
> :godmode:

Let's set a good example :wink:

Also are there any more of these? Would prefer to do them all in one go.

**Comment by astroash** [comment]
> Also are there any more of these? Would prefer to do them all in one go.

🤷‍♀️ I gittered everyone who owns a repo we use, so I'm just going through them as they respond. I can stick them in a WIP to be merged later if that's easier.

**Comment by eliascodes** [comment]
The node shell workshop in the resource list is actually wrong, we're using the one under the FAC org already, Marko's version is an old fork.

**Comment by eliascodes** [comment]
Sick of waiting, lets get it in.

**Comment by astroash** [comment]
@eliascodes I’ve got a few more to do. Can you wait a week?

**Comment by eliascodes** [comment]
@astroash 🕦 👀

**Comment by astroash** [comment]
@eliascodes 🙄

**Comment by astroash** [comment]
Decided to leave react workshops as external as creators said they wanted to use them elsewhere and will update. If we end up wanting to make our own changes we can duplicate them at that point. Also not moved any older as workshops as it will mess peeps currently updating them 😸

**Pull request merged**
