### PR TITLE
Week 7 - workshop1 presentation

### PR DESCRIPTION
**Pull request by alexis-l8**
Presentation link: https://drive.google.com/file/d/0BxXF_LZcFnS5ODM0dElWYmtmMWc/view

- If you click on 'Open with Google Slides', you'll find the notes section below the slides.
- The article from the end of the ReadMe will help a lot with the structure of the presentation: http://dustwell.com/how-to-handle-passwords-bcrypt.html
- Happy to walk to Nazareth and Gaza mentors through these slides if necessary. 

relates #550

### CODE REVIEW

**Comment by jsms90** [comment]
@mattlub please be aware. The presentation slides have speaker notes attached. I would definitely advise setting up a hangouts between @alexis-l8 and whoever is delivering this workshop in Nazareth

**Comment by mattlub** [comment]
@jsms90 @alexis-l8 thanks. So is this basically a walkthrough of the README of the following workshop?

**Comment by jsms90** [comment]
@mattlub See [the comments](https://github.com/foundersandcoders/master-reference/issues/550#issuecomment-320675160) in the issue

**Comment by ronanyeah** [comment]
@alexis-l8 What shall we do about this? It was great that we had this to paper over the cracks in Week 7 v1, but ongoing I assume we want to avoid having course content that isn't hosted on GitHub?

**Comment by jsms90** [comment]
@ronanyeah @iteles I completely agree that the curriculum should be documented in markdown files within github for the sake of version control & so that others can review and approve content.

But realistically, that comes down to the "philosophy of the curriculum" #591.

Better for us to include whatever material has been delivered (presentation slides or otherwise) in our documentation, so the curriculum can be iterated upon and improved for next time.

**Pull request merged**
