### PR TITLE
Additions to product build tech stack

### PR DESCRIPTION
**Pull request by eliascodes**
Was meant to be part of #227 but it got merged just before I managed to push changes.

* Adds Github/NPM/Install links for all options
* Adds a bit more intro text for some options
* Adds SASS (+ alternatives), Webpack (+ alternatives) and Babel
* Adds Linked contents section for quick nav

### CODE REVIEW

**Comment by jsms90** [comment]
Sorry @eliascodes!!! Didn't know we were waiting for anything more.

Looks so thoroughly :heart_eyes_cat: :heart_eyes_cat: :heart_eyes_cat:

**Comment by eliascodes** [comment]
@jsms90 that's OK, I didn't make it clear to anyone 😄

**Comment by des-des** [comment]
some small changes i am gonna drop in here as will otherwise forget

 * add the vanilla options to first list ie handlebars, postgres and hapi, jwts.

 * And browserify to webpack alternatives

**Comment by jsms90** [comment]
and move the "Advanced Javascript" section out from underneath the "Possible technologies" heading

**Pull request merged**
