### PR TITLE
Updated suggested APIs

### PR DESCRIPTION
**Pull request by tonylomax**

### CODE REVIEW

**Comment by gminova** [comment]
You have pasted the wrong link for postcodes API should be https://postcodes.io/

**Comment by Oliversw** [comment]
@tonylomax

**Comment by astroash** [comment]
IMO I don't thing any of these links should be added into MR. The Kayne West one is mocking someone who is known to have bipolar, and the others are localised and UK based, which excludes other campuses.

**Comment by Oliversw** [comment]
@astroash fair point on the Kanye API, but do you think it might be worth to create a section underneath with the UK specific APIs in that case? That way other campuses can also do the same if they find simliarly local APIs that they still want to record and share between cohorts

**Comment by astroash** [comment]
Yeah, sounds like a good idea 🙂

**Comment by tonylomax** [comment]
Sorry missed this, thanks @gminova and @astroash. I've removed Kanye and fixed the postcode link, also split them into different sections, what do we think?

**Pull request merged**
