### PR TITLE
Update readme for week 4

### PR DESCRIPTION
**Pull request by marisid**
- Add internal links to project spec and readme topics
- Minor edits for consistent formatting and wording
- Remove top instructions for mentors

### CODE REVIEW

**Comment by marisid** [comment]
Related to #30

**Comment by des-des** [comment]
@marisid @SavageWilliam please read the contributing.md file

**Comment by marisid** [comment]
@des-des we are expecting some minor edits (potentially) in the readme by @stevehopkinson, that's why I didn't delete the branch in case he wanted to use it. But thanks for the reminder :+1:

**Comment by des-des** [comment]
ok yeah jus you should assign the pull to somebody in the file to merge pulls. https://github.com/foundersandcoders/master-reference/blob/master/CONTRIBUTING.md. Maybe that should be more clear..?

Also, once a pull is closed other changes can be made on a new branch (it can have the same name).

**Comment by des-des** [comment]
@marisid @SavageWilliam ops my bad. Did not realise you were merging you own branches. Ignore me!

**Pull request merged**
