### PR TITLE
Update week 2 schedule

### PR DESCRIPTION
**Pull request by finnhodgkin**
Still needs final links from @oliverjam for the roman numerals code-along, the NPM intro and the introduction to testing and TDD readme.

+ adds intro to NPM
+ adds intro to testing and TDD
+ swaps learn-tdd for learn-tape
+ adds Roman numerals TDD code-along
+ adds new traffic lights callback morning challenge
+ changes pure functions description
+ clears external speaker slots
Relates #252 #253 #256 #327 #328 #330 #331 #346

### CODE REVIEW

**Comment by jsms90** [comment]
@finnhodgkin Looking great :heart:

**Comment by oliverjam** [comment]
@finnhodgkin @jsms90 Just to clarify — you need me to move my stuff into the Founders & Coders org to link them?

**Comment by jsms90** [comment]
@oliverjam [This guide](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/creation-of-resources.md) should help you figure out your options :+1:

**Comment by oliverjam** [comment]
Shit sorry, I just made a new PR because I forgot about this one. I'll move my changes to this branch

**Comment by jsms90** [comment]
@oliverjam So is this no longer a work in progress?

Could you also update the schedule for day 4 and 5 to reflect the [general week schedule](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/week-schedule.md) please? This week was only switched around for FAC10 because of Huw's availability :+1:

**Comment by oliverjam** [comment]
@jsms90 It's still a work in progress as I need to add the links to the npm and TDD readmes that I'm making today. I'll update the rest of the schedule too.

**Comment by oliverjam** [comment]
This is no longer a WIP, all the links should be correct now

**Comment by jsms90** [comment]
@eliascodes :woman_shrugging: Whoever's PR is merged second will just have to deal with the conflicts, right? No biggy

@finnhodgkin @oliverjam It is always good to make a branch & a PR per feature (e.g. section of the week) rather than per file (e.g. week-schedule.md).

The problem now is that I can't merge in features that are ready (e.g. the intro to npm) without also merging in features that aren't ready (e.g. the code-along not having a screen-recording for Nazareth & Gaza mentors to use).

@oliverjam @finnhodgkin How far away are we from having all of your other issues complete?

**Comment by oliverjam** [comment]
@jsms90 I'm working on the screencast this afternoon. It might take a while to upload as it's gonna be an hour of 2k video. Do you not want to merge this until the screencast is online?

I'll also have the edits to the Project readme done this afternoon.

**Comment by jsms90** [comment]
@oliverjam The only thing that I want to avoid, is merging something into `master-reference` that is not ready for delivery at all of our campuses. After all, mentors in Nazareth and Gaza will be using this to try and prepare, and it's much to deliver material that you yourself have designed.

If they see your solution branch, they may be able to work backwards from it. But if that proves to be a bit much, they may need to revert to the old material. I know that you are working on this and it will likely be done before delivery for FAC11, but I am loathe to merge something in until it is actually ready for consumption in all locations.

We may need to make an exception for this, since mentors in Nazareth don't have long to prepare for a week that is changing very drastically, but does that make sense?

**Comment by oliverjam** [comment]
@jsms90 Yup. The screencast will definitely be done today, so it's probably fine to merge the schedule so mentors can at least start preparing the other parts of the week.

**Comment by jsms90** [comment]
If it will be done today, we can wait for everything to be complete before merging :+1:

**Comment by jsms90** [comment]
@oliverjam @finnhodgkin I really appreciate exactly how much work has gone into this already :clap: Hats off to you both. Just one last thing we need before this PR can be merged in.

This week is undergoing two fundamental shifts, that has come from [a proposal to switch to tape](https://github.com/foundersandcoders/master-reference/issues/253) and [a proposal to change the project to a to-do app](https://github.com/foundersandcoders/master-reference/issues/256). Historically, the curriculum has experienced flip flopping, with one cohort taking something out because they didn't personally like it and the next making their own personal decision, etc. We need to start basing our decisions on evidence and recording our hypotheses.

Please follow @iteles' advice:
> If you're going to go ahead an introduce tape in week 2, could I please ask that a few hypotheses are created stemming from this proposal before week 2 so that we can accurately measure and record the results (to help make a qualified and data-driven decision so that we can spare you guys from listening to the same discussions over and over again too)? :pray:

As requested [here](https://github.com/foundersandcoders/master-reference/issues/253#issuecomment-310835278), please post a comment in the following format **within each of the two relevant proposal issues** (mentioned above).

### Problem
_This can include a description and also any evidence (e.g. feedback during SGCs)_

### Solution
_This is likely to be a detailed description of the changes you have now already made_

### Hypothesis
_This is the outcome that you expect i.e. the impact on the student experience that you expect / intend this change to have_

Thanks again for your time guys :exclamation: and for taking on a pretty big task with this week :medal_sports:

**Comment by oliverjam** [comment]
@jsms90 We ended up with one comment that pretty much covered both proposals, so I've copied it into both threads.

**Pull request merged**
