### PR TITLE
Move presentations later on fridays

### LINKED ISSUE #196: Swap order of play on Friday afternoon
The end of the day currently looks like this: 

> 15:00-16:20 - Presentations (20 mins per group)
16:20-17:00 - Team Retrospectives (Team S-G-C)
17:00-18:00 - External Speaker or Upstairs Project

Let me suggest:

> 15:00-15:40 - Team Retrospectives (Team S-G-C)
15:40-17:00 - Presentations (20 mins per group)
17:00-18:00 - External Speaker or Upstairs Project

This is so that if the external speaker wants to, they can sit in on the presentations without having to then wait around during the team retrospectives.

### PR DESCRIPTION
**Pull request by jsms90**
External speakers are now being contacted and offered the opportunity to watch presentations and code review

+ move presentations right before external speaker slot on fridays

Fixes #196

### CODE REVIEW

**Comment by des-des** [comment]
@jsms90 Is this for london, or for all campuses?

**Comment by jsms90** [comment]
@des-des Do you think there is a benefit to it being the old way round?

**Comment by des-des** [comment]
@jsms90 I do not have an opinion, was only asking the question

**Comment by jsms90** [comment]
@des-des Fair enough. I reckon all campuses, insofar as speaker slots have ever been all campuses. We spoke about day 5 (Thursday) in Nazareth not being an ideal time for an external speaker to come in. But as far as I know, external speakers have been few and far between (so far) anyway. Is that right?

Now that Nazareth has alumni, we could theoretically have mentors showcasing the projects they have made?

**Pull request merged**
