### PR TITLE
Remove duplicated "introduce research topics" from week 8 schedule

### PR DESCRIPTION
**Pull request by MarwaBj**
#831

### CODE REVIEW

**Comment by m4v15** [comment]
Hey @MarwaBj is this ready to be merged?

**Comment by MarwaBj** [comment]
sure @m4v15  it's ready :+1:

**Comment by eliascodes** [comment]
@MarwaBj as per the instructions in the week epic issue #829, please assign myself and @m4v15 when work is ready to review:

>  the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)

Otherwise we won't know when work is ready to review and it might not get merged.

**Comment by MarwaBj** [comment]
Done @eliascodes  and this request ready to merge :+1:

**Pull request merged**
