### PR TITLE
update resources md

### PR DESCRIPTION
**Pull request by lucyrose93**
added Flexbox, software architecture, and modular pattern resources. relates #358

### CODE REVIEW

**Comment by jsms90** [comment]
@edgarfinn Please do not merge anything into master without the review of the maintainers of this repo. We also require the approval of 2 reviewers first.

Please read the [contributing guidelines](https://github.com/foundersandcoders/master-reference/blob/master/CONTRIBUTING.md)

**Comment by edgarfinn** [comment]
Sorry my bad. Reverted now

**Comment by jsms90** [comment]
Thanks @edgarfinn, but no I think you're fine. I can't see anything contentious in here :smile: 

Just be mindful of the [contributing guidelines](https://github.com/foundersandcoders/master-reference/blob/master/CONTRIBUTING.md) :+1:

**Comment by edgarfinn** [comment]
👍

**Pull request merged**
