### PR TITLE
Add database testing workshop to readme for week-6 

### LINKED ISSUE #776: Introduce workshop on testing database queries in Week 6
Currently week 6 research topics include testing databases. FAC11 found it impossible to find information on it, that's why we decided to introduce [database queries testing workshop](https://github.com/foundersandcoders/ws-database-testing) instead of this research topic.

This workshop is designed to be 1 hour long to be run before research afternoon, so the other topics can still take place.

### PR DESCRIPTION
**Pull request by azayneeva**
Fixes #776 

- added workshop link in readme;
- updated timings to include workshop;
- removed testing from research topics

### CODE REVIEW

**Comment by eliascodes** [comment]
Has this been discussed with the mentors leading week 6 in other campuses? I saw no discussion of this workshop in the week-6 epic #633.

If you guys want to run this in London I see no issue, but I'm not sure it's fair to change the actual week schedule for the other campuses as well, as the mentors there may feel compelled to follow the schedule and therefore have to get to grips with a new workshop with little time left before their weeks start.

**Comment by astroash** [comment]
@eliascodes yeah, there's no need for this to be merged for this time round for Gaza & Nazareth as it's super short notice. I thought it would be useful to document this in the form of a pull request so current mentors/cfs can discuss, and it's ready to be looked at next time round.

There's potentially some other _last minute_ workshops coming in in London, do you think this is a useful way to document, or is it better to leave these additions in an issue?

**Comment by eliascodes** [comment]
@shiryz @mantagen @ibraghada was this workshop was run in Nazareth or Gaza? It would be good to know so we can decide whether or not to merge this as is.

**Comment by shiryz** [comment]
@eliascodes yeah we added it to the Naz schedule

**Comment by eliascodes** [comment]
@ibraghada any word on whether this workshop was run in Gaza?

**Comment by matthewdking** [comment]
@eliascodes - @ibraghada correct me if I'm wrong but I believe this workshop was ran in Gaza for G3. I remember chatting to a couple of the students about testing databases in their student projects.

It would be good to get this merged in before week 6 if possible :smile:

**Comment by eliascodes** [comment]
@matthewdking yeah, I asked for those mentors in Gaza who are doing week 6 to be assigned as reviewers to this issue, because in #827, we ask that all mentors doing week 6 approve this PR to make sure they understand that it's being added to the schedule.

But I've had no response. @ibraghada @aajour what's the story? Did the Gaza mentors do this workshop, and/or are they prepared to give the workshop for FACG4?

**Comment by eliascodes** [comment]
OK well I've not heard anything from anyone in Gaza about this, so I'm going to merge this tomorrow, 5pm GMT.

**Comment by eliascodes** [comment]
lol, well I missed the deadline I imposed on myself 😅

**Pull request merged**
