### PR TITLE
Create initial skeleton of code review notes

### PR DESCRIPTION
**Pull request by eliascodes**
~~**DO NOT MERGE**~~

Related to #650 

I've made this PR simply to share my initial thoughts. ~~This should _not_ be merged in its current state.~~

The list at the moment is just some very terse bullet points of the stuff that should be covered in a good and complete code review. I want to invite comments on the content so far, the structure, and any missing aspects that should be included.

I've yet to include any examples of good code reviews, but I think this is a good idea.

### CODE REVIEW

**Comment by veredrec** [comment]
@eliascodes I think this is a great guide. I found [this general guide](https://github.com/thoughtbot/guides/tree/master/code-review)  on how to review each other's code. It might be worth linking to it in the guide you are working on.

**Comment by sofer** [comment]
I am kind of in favour of merging it, even in its current state, so that people can start adding some flesh to the bones.

**Comment by sofer** [comment]
I also agree with @veredrec that a style guide which includes advice like *"Don't use sarcasm"* would be very useful.

**Comment by eliascodes** [comment]
OK if people want this merged I guess it can go in as a starting point, but would like at least one of @des-des and @ZooeyMiller to review it before hand.

@veredrec @sofer I've added a simple list of points from the style guide you pointed to, if you think I missed something important let me know 👍

**Comment by veredrec** [comment]
@eliascodes it looks good to me! :+1:

**Comment by eliascodes** [comment]
Thanks @sofer @ZooeyMiller, either of you can merge 👍

**Pull request merged**
