### PR TITLE
Toolkit week - learning outcomes, week structure & some research topics

### PR DESCRIPTION
**Pull request by jsms90**
Related #24

### CODE REVIEW

**Comment by njsfield** [comment]
I've made a PR for the project outline, and will be making a PR with the morning challenge and refactoring workshop link

**Comment by jsms90** [comment]
@des-des Changes done :+1: 

It's definitelly not the final product. I'm really sorry this is so last minute! But rest assured, @njsfield  is almost done with all of his work and I'm dedicating all of Friday to finishing the Accessibility and Git workshops.

**Comment by Jbarget** [comment]
@des-des @bradreeder is this ready to merge?

**Comment by des-des** [comment]
Awesome!

**Pull request merged**
