### PR TITLE
extra time for linting

### PR DESCRIPTION
**Pull request by starsuit**
change the intro to linting workshop time to be 1hr - doubt it will take this long but we definitely need more than 15 minutes.

### CODE REVIEW

**Comment by astroash** [comment]
The timeslot was originally set short as this was intended to be a document that was highlighted to students to complete on their own time during project setup. Is this now intended as a mentor lead exercise? It's worth clarifying it's purpose as 1hr implies it is a workshop.

**Comment by starsuit** [comment]
I think we would like this to be more mentor-led - my cohort didn't realise this was something we had to go back to and many of us never even had linting set up with VSCode/Atom before our student projects.

@bantek89 and I thought it would be good to get students into project groups, have them initialise a project repo, then go through the linting workshop, ensuring each group has linting enabled and everyone starts to think of linting as an important project step

**Comment by oliverjam** [comment]
> get students into project groups, have them initialise a project repo, then go through the linting workshop

This is what I did for FAC16's React Week project setup, and I think it went pretty well. Everyone ended up with a properly set up repo deployed to Netlify, which was a good base for them to go into the projects from

I'm not sure you'll need an entire hour though, could easily fit into 30 mins

**Comment by teenie-quaggard** [comment]
> get students into project groups, have them initialise a project repo, then go through the linting workshop

This sounds great as we had the same problem in our cohort. Can you put together a bit of documentation of this process and share it?

**Comment by starsuit** [comment]
>Can you put together a bit of documentation of this process and share it?

Not sure what the documentation would be, if students already know how to set up a repo? Maybe we could add a line in the linting workshop saying to get into project groups and set up a repo. This would probably act as a reminder for mentors too.

>I'm not sure you'll need an entire hour though, could easily fit into 30 mins.

Yeah 30 mins sounds about right, I guess we can see how long it takes us when we do it and if we need more time we can change.

**Comment by teenie-quaggard** [comment]
> Maybe we could add a line in the linting workshop saying to get into project groups and set up a repo. This would probably act as a reminder for mentors too.

Sure that sounds good. Maybe just see how it goes, and make notes on things that people get stuck on so that the sticky parts can be better documented for the next cohort.

**Comment by astroash** [comment]
> Can you put together a bit of documentation of this process and share it?
This should be covered by the Dev Ops project roles 

https://github.com/foundersandcoders/london-programme/blob/cde61dafaa06aa629baf86673ba0cee5dd572f70/course/weeks-10-18/project-roles.md

**Pull request merged**
