### PR TITLE
change git workshop link from original to forked version

### PR DESCRIPTION
**Pull request by jsms90**
Forked version has lots of content removed, to update the tutorial to be more relevant for the current prereqs & precourse.

### CODE REVIEW

**Comment by nogainbar** [comment]
cool, sounds good!
:)

thanx!

**Comment by nelsonic** [comment]
@jsms90 it's _great_ that you have streamlined @NataliaLKB's Git Tutorial. 🎉 
The https://github.com/jsms90/learn-git-basics/commits/master 👍 
Was this discussed in an issue somewhere?

**Comment by nelsonic** [comment]
@bradreeder I'm _unclear_ on the F&C [CONTRIBUTING.md#pull-requests](https://github.com/foundersandcoders/master-reference/blob/d799a804f2a2dd3561a62de1b1becee0d1601475/CONTRIBUTING.md#pull-requests) workflow... should changes be _approved_ by the reviewers `before` PRs are _merged_?
image
Also, I'm _sure_ you guys discussed the improvements _verbally_, but I don't see an **issue** on 
https://github.com/foundersandcoders/master-reference/issues ***or*** https://github.com/NataliaLKB/learn-git-basics/issues where these improvements were proposed/discussed which _could_ have been referenced in the commit message... 🤔

**Comment by NataliaLKB** [comment]
@nelsonic Thanks for the mention! 

Yes @jsms90 feel free to make a PR to the upstream of your forked branch to update it with changes. Always good to get people contributing! 

👍

**Comment by bradreeder** [comment]
@nelsonic I plan to have a discussion with FAC9 about the contribution guidelines as I agree the process is pretty lax right now.

A lot of PRs are coming in last minute and I have to make a decision as a facilitator whether to merge so that the students coursebook is up to date on the day and the day goes smoothly, or close the PR and ask that the mentor re-do it properly --  stressing out the mentor whose trying to lead a day and potentially leading to complications.

Action points from me:

* I'll pressure mentors to prepare the next weeks in advance, and make sure that mentors are notified of the contribution process, so we can avoid this issue from now on. 
* I'll make sure we designate more time to curriculum-planning in the next iteration. 

The only way our process can guarantee that things will be finished properly and before the start-date is by making mentors complete the curriculum coursebook within curriculum hours. Every FAC I've experienced has prepared their course material last minute. I take this as an indication that the problem does not lie in people -- our mentors are over-worked and trying their best --  but that it's a recurring problem to do with our processes & the time we give mentors to organise their weeks.

**Comment by des-des** [comment]
@nelsonic I think when @bradreeder merges there is implicit approval?

**Comment by nelsonic** [comment]
implicit approval indeed ... 😉 
We should _all_ know better than to _imply_ anything. 
Especially on a PR that makes no reference to an issue and switches a link to a personal fork of a learning resource without any attempt made to discuss the improvement with the original author...
But I guess it's better than the `commit-direct-to-master` that's _still_ going on in other places ... 👍 
Anyway... hope you're well @des-des ❤️ 
the photo of Nazareth https://twitter.com/lovemantagen/status/833306352147693568 looks good!

**Comment by jsms90** [comment]
@nelsonic @NataliaLKB 
Completely agreed! I would never normally fork an open source repo and just change it without raising an issue and/or making a PR first, let alone when it is a workshop for FAC members created by a FAC member, let alone when it's a tutorial on git practices....absolutely right, _TOTAL_ IRONY. I'm really sorry @NataliaLKB, because this must have seemed really rude and disrespectful (not to mention bad git practice @nelsonic :sweat: )!

It's 100% just down to my own poor time management and the fact that I was still panic planning at 4am
image

I was originally intending to make my own very different tutorial, using the fact that FAC10 have been asked to make their own websites as part of the prereqs. (Kind of like I did for the [accessibility workshop](https://github.com/jsms90/web-accessibility), but much more involved). Not because this tutorial is bad, but FAC10 have had more experience with git than previous cohorts, and can do more than this in 2 hours.

[I just ran out of time and chose to prioritise creating an accessibility workshop, because I knew I had a solid git workshop to fall back on](https://github.com/foundersandcoders/master-reference/issues/24#issuecomment-280845211). I :heart: good workflow so much :sweat_smile: and there were so many times in FAC9 when people were struggling because they weren't clear on the commands, let alone the overall flow. So I've been thinking about how to write this workshop for a really really long time. Tbh I'm heartbroken not to have it complete, and not to see it get used. I shouldn't have relied on having a week off after the end of FAC9, and certainly shouldn't have left so much of my curriculum planning until then.

But @NataliaLKB I really, really meant no disrespect!! I found your tutorial when I was applying for FAC and it really helped me. I just felt guilty enough for not leaving enough time to make the workshop I had intended to. I would have felt even worse if I hadn't even tailored it to the current cohort. So I ended up making a bad choice, forking and changing it, just so it would get merged in time for Nazareth's day 2....nothing good happens after 2am :sweat_smile:

**Pull request merged**
