### PR TITLE
Update Heroku resources link

### PR DESCRIPTION
**Pull request by shannonjensen**
This is to include a link to the heroku cheatsheet @hannahcmtucker put together for the week4 project description.

### CODE REVIEW

**Comment by matthewdking** [comment]
I think it is a great idea to have a Heroku cheat sheet of some sort :+1: 

A few things to consider:
- this cheat sheet includes database related things which aren't covered until week 6 - this could be resolved by moving these commands to a database specific section?
- would it be better as an markdown file within this week rather than a link to a hackmd?

**Comment by zurda** [comment]
Is this ready to be merged, or should it into week-4 as a MD file instead, as @m4v15 suggested? Happy to help with this PR if needed

**Comment by m4v15** [comment]
Assigning the others - I think it makes more sense to be a md file here (so we know if it gets changed) but I'm ok with it being merged as is

**Comment by astroash** [comment]
@zurda it would be great if you could make the contents of the hackmd a md file 🙏🏽. This way we are not reliant on 3rd party hosting, with the potential of students editting the contents 😊

**Comment by zurda** [comment]
Closing this as there are conflicting files, and there's a more up to date PR: https://github.com/foundersandcoders/master-reference/pull/991

**Pull request closed without merging**
