### PR TITLE
add links to schedule & update formatting

### PR DESCRIPTION
**Pull request by jsms90**
relates #24

+ Maybe we want to remove _any_ mention of particular Founders and Coders campuses in the future? But for now, I think it makes sense to have links to London & Nazareth, so that they can navigate between all our repos easily? e.g.
> Campus-specific information - London, Nazareth
> Structure of Github organisation & repositories - London, Nazareth

+ @des-des I've added a link to a FAC1-Nazareth organisation (that doesn't exist yet). Do you want me to make it, or do you want to make it? Can I suggest that you ask the Nazareth students to follow [this repo naming convention](https://github.com/foundersandcoders/master-reference/issues/24#issuecomment-280699826) too

+ Should we move the stop-go-continue.md files from `master reference` into `london-curriculum`? Right now, London and Nazareth students would be contributing to the same file...or is that good?

+ I don't have a link to whatever @Cleop is doing for the Intro to pair programming, so I have just linked to the generic pair-programming.md for now

+ I don't have links to Nick's morning challenge for day 3

### CODE REVIEW

**Comment by bradreeder** [comment]
@jsms90 One step ahead of you on stop-go-continue. See #114 

I think adding organisational links into the coursebook would be a good idea as a quick provision.

@des-des What do you think of me adding to the [title](https://github.com/foundersandcoders/master-reference/tree/master/coursebook) page of the coursebook:

* Links to relevant London & Nazareth repos (inc. stuff like london-curriculum which contains London campus info)
* Links to relevant FAC10/ FAC1 Nazareth github organisation repos

Let me know what Nazareth repos need to be added if so.

**Comment by bradreeder** [comment]
@jsms90 sorry Jen, just reviewed your file and noticed you've already added this. Looks good. @des-des could you provide links to the relevant Nazareth repos?

**Comment by bradreeder** [comment]
@jsms90 One step ahead of you on stop-go-continue. See #114 

I think adding organisational links into the coursebook is a good idea as a provision until we decide how we're going to store the curriculum next time. Looks good.

@des-des Could you let us know what the relevant Nazareth repos are so we can add them in as well?

**Comment by jsms90** [comment]
@bradreeder 
> Could you let us know what the relevant Nazareth repos are so we can add them in as well?

The only london-specific repos are:
+ https://github.com/foundersandcoders/london-curriculum - I thought we said at the Curriculum Committee that there wasn't going to be a Nazareth one for now? But @des-des it might be worth creating one, even if it's purely for s-g-cs atm?
+ https://github.com/FAC10 - @des-des, unless you have made one already, if you make one called `FAC1-Nazareth`, my links will work ;)

**Comment by jsms90** [comment]
Just getting another cheeky addition in there, since neither of you have started a review yet ;)

Added a menu like https://github.com/foundersandcoders/master-reference/blob/c3f5e4c3f63f88fa2895a0029a015f118041ed28/coursebook/week-2/README.md

**Comment by des-des** [comment]
@jsms90 sorry, made one called https://github.com/FACN1. (being inconvenient). I can go and do a replace all

**Comment by jsms90** [comment]
@des-des good to go :tada:

**Pull request merged**
