### PR TITLE
Add learning outcomes for Node week 2.

### PR DESCRIPTION
**Pull request by RhodesPeter**
Related #31

### CODE REVIEW

**Comment by msachi** [comment]
@RhodesPeter The following will not be covered (at least not in the Node shell workshop):
- Publishing your package on npm
- The tap-nyan test runner!
- Create your own test-runner

Commands 'cat', 'ls' and 'grep': grep will not be covered. I would omit this line (it is covered under shell scripting)

Streams is also repeated

**Comment by RhodesPeter** [comment]
Thank you @msachi. I have made these changes 😀

**Comment by njsfield** [comment]
Sweet, looks good :)

**Comment by esraajb** [comment]
Ill merge for now, as we need to use it tomorrow. feel free to review it later.
thanks alot @RhodesPeter

**Pull request merged**
