### PR TITLE
Update precourse documents

### PR DESCRIPTION
**Pull request by jsms90**
From your [curriculum planning](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/london-initial-planning.md#pre-course-material) & an in-person conversation with @alexis-l8 & @yvonne-liu, we have distilled this down into the following changes:
+ Remove first paragraph beginning with "F&C is an intense course"
+ Provide numbered list at the top of the precourse page, so that students are aware of all the content and don't miss what's at the bottom i.e. the calculator project
+ Move "DOM manipulation" to "required"
+ Move calculator project to "required"
+ Move "JavaScript" section to "recommended"
+ Clarify what is _required_ before the course
  + Remove "recommended" section from the page itself, so that there is no potential for interpretation.
  + Put this list on a separate page & link to it at the bottom of the precourse page itself
+ Move learning objectives from separate file - add each one into the section of the precourse page itself
+ Add explanation of npm package manager to installation list (& what node is?)

@alexis-l8 & @yvonne-liu Please add your reviews asap. If you would like any of the rest of your cohort to review before you merge, please add them to the "reviewers" list & notify them on gitter/whatsapp. When you are ready, please merge this document and notify @bradreeder immediately.

**We are aiming to notify FAC11 today!** :tada: 

Relates #257

### CODE REVIEW

**Comment by jsms90** [comment]
@alexis-l8
This is a great little gem!! And it's awesome that it's not too long as well! :heart_eyes: 
This sounds like the _perfect_ type of resource to give people to read over the weekend before week 4 starts (if your cohort decides to do that).
+ It gives a really nice intro to what node can be used for, other than just building web servers.
+ After 3 weeks of the course, students are also less likely to be terrified by a long list of words that mean nothing to them.
+ Students will know that if there's anything they didn't understand, they're just about to have a week on it, so they shouldn't worry.

**But** _a word of caution._ It is very easy at this point in your course to forget just how far you have come in 16 weeks.

Listen to the beginning of the video, where he gives you an indication of who his target audience is
> I've had a lot of people ask me this. People are saying stuff like, "Hey, I've been doing PHP for a lot of years..."

He then starts talking about the V8 engine, listening to network traffic, HTTP requests, accessing databases
> basically anything you could do with PHP and Ruby on Rails

He then mentions "utilities" and starts reeling off a list of names, without explaining what any of that means.

He starts talking about "modules in node" without _reeeally_ explaining what a module is
> If you've used require.js you already know the concept

He starts on the specifics of how you actually write things in node e.g. require, module.exports without fully explaining them. This should probably be left to week 4.

I could go on.

**Comment by jsms90** [comment]
What problem are we trying to solve with putting this video into the precourse?

It seems to me that this suggestion came from the fact that some people on your course were familiar enough with node to start using it a little bit in projects before week 4. Others weren't familiar and maybe it seemed a bit daunting, like they weren't well prepared?

I'm not convinced that this division in your cohort is best fixed by getting everyone up to speed with the basics of node before they arrive. Plus, if it is the optional section, we might end up increasing the divide because some people will have watched it and others will not.

Besides that, I believe that @lucymonie was referring to a more high level overview of what a back end is, and how a front end and back end might speak to one another? Is that fair, Lucy? @alexis-l8 Did you see that we added "Art of Node" within the installation list, for those who are curious enough to want more explanation? I think that keeping the explanation at this kind of high level, article-based level is best.

But I am also really keen to make sure we learn from your cohort and everyone's feedback!! This is just a word of caution for you to think about. If you guys decide you want this video in there, I'm happy to oblige.

**Comment by alexis-l8** [comment]
@jsms90 I'm with you all the way. You're right in that we forget how much better we've got. I'm happy to stick with Art of Node in the installation list :)

I'm also happy with the rest of the pre-course. Thanks again for sorting this all out!

**Comment by bradreeder** [comment]
screen shot 2017-05-19 at 16 54 13

Looks good to me. 👍

**Comment by oliverjam** [comment]
I still disagree with forbidding them from learning flexbox. Seems weird to completely disallow something that's been in some browsers since 2009. Even if we don't want them to use it in projects (I used it in all of mine) it's still a fundamental part of learning CSS layout.

Also it confused me that it was lumped in with bootstrap and jquery. That might lead some people who don't know CSS that well to assume it's not a native feature.

**Comment by oliverjam** [comment]
This kind of relates to ES6 as well. We never specify browser support in project specs so it's not clear if we're trying to do legacy support or not. It's important to learn how to support old browsers but not at the expense of learning how to do things properly.

**Comment by bradreeder** [comment]
@oliverjam Agreed, I think this was a point we missed. We've opened a PR here if you could review / merge? #267

**Comment by lucymonie** [comment]
@jsms90 did you mean to refer to @lucyrose93 above? I'm not clear what you mean. :kissing:

**Pull request merged**
