### PR TITLE
Add pastoral care time

### PR DESCRIPTION
**Pull request by sofer**
Addresses #563

### CODE REVIEW

**Comment by jsms90** [comment]
@eliascodes Personally, I think this is necessary. A lot happens each week in FAC :sweat_smile:

**Comment by shiryz** [comment]
@eliascodes adding to what @jsms90 said, doing a walk every week is the same as every 2/3 weeks, instead of doing a 15 mins walk it's divided to 5 mins walks.

**Comment by jsms90** [comment]
@shiryz a 5 minute walk? I don't think there's any way you can having a meaningful pastoral care conversation in 5 minutes

**Comment by sofer** [comment]
@eliascodes I did not mean to imply that they would have to happen every week, but that if they are happening, Day 4 is the day to do them.

**Comment by des-des** [comment]
@sofer process pls

**Pull request merged**
