### PR TITLE
New Schedule, Possibly WIP

### PR DESCRIPTION
**Pull request by m4v15**
Hey so this is something I've been thinking about for a while, how the readme's for each week are a bit overly specific (scheduling toilet breaks!) and not necessarily universal across campus (with timings and such), and also quite hard to read at a glance.

This isn't necessarily the solution but I definitely think it's an improvement and it's probably something I would do for the rest of the weeks if you guys agree.

@eliascodes and @shiryz this could also fold into the long term idea of having a schedule with guidance on when to teach things and with links for those things below?

n.b.
- I have removed the campus specific links for scavenger hunt as I think they can just be linked by the CF at the time and it's not scalable to have them all here all the time?
- I've merged the introduction specificity just into "Welcome fun" - I guess _might_ need notes to explain exactly what that means but from my experience the first day often changes cohort to cohort and campus to campus

### CODE REVIEW

**Comment by m4v15** [comment]
Sorry I meant to be clear, not sure if we definitely want to merge this yet, but just wanted some eyes on it to see what people think 👀

**Comment by m4v15** [comment]
> I'm gonna be a bit pedantic about the "naming convention" though 

Do you just mean where I've been lazy in the names in the table... yeah my bad.

>I'm not sure what would be best but maybe keep the links in the table as well as a suggested schedule, it might be redundant but won't be in the future when more links are added

Yeah we could keep the links in the table, it would just look messy in the raw markdown and might be a hassle to maintain - also some workshops have multiple links which looks messy in MD's bad table formats so I just went with this for now.

When you say as well as a suggested schedule do you mean what I have already, or be more specific with times? I was thinking that just showing the order (i.e. top to bottom) was suggestive enough

**Comment by shiryz** [comment]
> When you say as well as a suggested schedule do you mean what I have already, or be more specific with times?

Yup what you already have, I was thinking that extra WSs wouldn't go into the table

**Comment by zurda** [comment]
Is this a WIP? Personally, I remember being confused about the toilette breaks, but my concerns were gone once day 1 was over :) 
I'm happy to help with the PR, if needed, since it has conflicting files

**Comment by m4v15** [comment]
@zurda Yeah I guess I kind of dropped this one a bit/it was an experiment to see what people thought - if @oliverjam @astroash like this style, I think if you address the conflicts and maybe do @eliascodes suggestion it can be merged, as I still feel like it is an improvement to the current readme

Thanks 🎉

**Comment by zurda** [comment]
I think one of the problems this PR was aimed to solved is also addressed here https://github.com/foundersandcoders/master-reference/pull/1004 . Am I correct?

**Comment by sofer** [comment]
@m4v15 Closing because addressed by #1004, which was inspired by this pr.

**Pull request closed without merging**
