### PR TITLE
Added async js topics to research topics: week 2

### PR DESCRIPTION
**Pull request by zurda**
Addresses #957, #956

### CODE REVIEW

**Comment by astroash** [comment]
@zurda has this change been discussed with other campuses/mentors?

**Comment by zurda** [comment]
@astroash , not yet, thanks for the heads up! We'll run this by everyone and create a PR if approved.

**Comment by astroash** [comment]
@zurda you can leave this open, will just wait to merge 😊

**Comment by zurda** [comment]
@astroash I'm happy to create it again once everyone weighs in on the [discussion](https://github.com/foundersandcoders/master-reference/issues/957) ( and we could still display these new topic questions to FAC-16 despite it not being in master-reference).

**Comment by astroash** [comment]
Reopened as I think this a valuable suggestion and I don't want it to get forgotten about ✨

**Comment by zurda** [comment]
It's worth noting the issue about week 2 where we summarised how using this branch went with FAC-16 (in short: it went well): https://github.com/foundersandcoders/master-reference/issues/933

**Comment by charlielafosse** [comment]
+1 would just like to pitch in and say that this new research topic went really well, and I think it'll really help to introduce those concepts at a slightly earlier stage :sunflower:

**Comment by astroash** [comment]
@m4v15 will leave you to merge if you're happy with the changes for al khalil

**Pull request merged**
