### PR TITLE
new default schedule

### PR DESCRIPTION
**Pull request by sofer**
~~Not quite ready to merge, as I am still waiting for confirmation of Gaza timetable.~~

### CODE REVIEW

**Comment by sofer** [comment]
@ishak52 has confirmed the Gaza times.

**Comment by sofer** [comment]
Actually, it turns out that the schedule in Gaza shifts in the Winter to 8am-4pm. Maybe it is unhelpful to have campus-specific start times and it might be better to just have indicative start times at 8:00, 9:00 and 10:00.

**Comment by astroash** [comment]
Someone should make a chrome extension that replaces timing place holders with campus specific times 🤓

**Comment by sofer** [comment]
Have removed times.

**Pull request merged**
