### PR TITLE
Change Node shell workshop link

### PR DESCRIPTION
**Pull request by msachi**
Now it points to my fork of Bradley's workshop (shortened version)

### CODE REVIEW

**Comment by jsms90** [comment]
@msachi Can you not make a PR to merge your forked version into @bradreeder's original?

**Comment by msachi** [comment]
@jsms90 It's a shortened version, I wouldn't want @bradreeder's additional content to get lost

**Comment by bradreeder** [comment]
@msachi In hindsight, I should have asked to PR any clarifications that were needed in the phrasing then you could've shortened it by asking the students to only do certain exercises, and the others if they find the time. But that's my bad and I wouldn't want to waste the time you've put into this. 👍 

@jsms90 We need to work out a uniform format for contributing to existing repos for next curriculum planning, until then I'm fine with this as I don't have the time to review.

**Comment by msachi** [comment]
@bradreeder I agree that would have been a better way to go about it. I think what I wanted to do is pick the most important bits and combine them in new ways (e.g. do just one of cat/ls/grep, but still introduce options), so shortening necessarily involved some modifying. But I didn't really change all that much.

I think it's fine for now, but at some point in the future I can make a list of enhancements / clarifications and you can just modify your longer version of the workshop.

**Comment by jsms90** [comment]
Yeah, no accusation intended @msachi. Just trying to make sure we learn from past mistakes i.e. me doing the exact same thing with Natalia's git workshop in week 1.

But I imagine that this one will cause less problems, especially if they don't want to raise any issues with the workshop

**Pull request merged**
