### PR TITLE
Change link to makemehapi workshop back to original

### LINKED ISSUE #211: link to an instructions file, which references the original makemehapi repo
I know that the week 7 mentors were considering making changes to some of the exercises, but it doesn't look like that has happened?

We can still raise issues on the original, and see whether Matt Hernandez is accepting PRs. But in the meantime, let's just link directly to the original repo? It would make it much easier for students to submit issues, and I'm not sure what the forked version adds?

https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-7/README.md
https://github.com/msachi/makemehapi

### PR DESCRIPTION
**Pull request by msachi**
Fixes #211

### CODE REVIEW

**Comment by jsms90** [comment]
@msachi You can change the keyword in the body of this PR to "fixes", just so the issue gets closed automatically :+1:

**Comment by jsms90** [comment]
@msachi Happy for us to merge?

**Comment by msachi** [comment]
@jsms90 I will add an md file as discussed, so the link will change to point to it.

**Comment by jsms90** [comment]
@msachi cool. Gonna close this then :+1:

**Pull request closed without merging**
