### PR TITLE
delete curriculum overview

### LINKED ISSUE #530: Curriculum overview inconsistent with week definitions
In the process of raising #529, I saw that the curriculum overview has become inconsistent with the contents of the new weeks. For example:

#### Week 2
* Talks about QUnit, which has been removed
* Talks about waterfall, which has been removed
* Talks about async testing, which has been removed

#### Week 3
* Talks about chrome inspector, which isn't part of the curriculum

#### Week 5
* Talks about commit hooks, which aren't part of the curriculum

#### Week 7/8
* Talk about hapi.js, which has been removed

Either updating the overview needs to be part of the tasks of updating a week, or we should just delete the overview, if its only purpose is to create a maintenance burden.

I favour the latter; I've never really looked at this file before today.

### PR DESCRIPTION
**Pull request by eliascodes**
fixes #530

### CODE REVIEW

**Comment by des-des** [comment]
hmm, I am generally in favour of the **idea** of some sort of overview file, but not defending implementation. Know what I mean?

**Comment by des-des** [comment]
Could we have an overview in each week / do we already?, then we could have a document that is just a set of links

**Comment by eliascodes** [comment]
@des-des we have [this](https://github.com/foundersandcoders/master-reference#curriculum) for top level, and then [this](https://github.com/foundersandcoders/master-reference/tree/master/coursebook#coursebook) is your set of links, and then for each week something like [this](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/README.md#toolkit-week). Seems good enough to me.

**Comment by des-des** [comment]
@eliascodes lol so many overviews

**Pull request merged**
