### PR TITLE
Add link to duplicated pure-functions workshop 

### LINKED ISSUE #759: Status of "Pure Functions Easy Testing" workshop
At the moment, the version that has been used for the current cohorts (FAC12, N3 and G3) is a [forked version in the Founders and Coders organisation](https://github.com/foundersandcoders/pure-functions-easy-testing), however [the original one](https://github.com/Jwhiles/pure-functions-easy-testing) owned by @Jwhiles still exists. 

Are we planning to PR to @Jwhiles' repo? Or ask to move the original repo under the founderandcoders organisation? Or stay with using the forked version? 

Using a fork has its downsides as it means we can't have issues for the fork, which is a shame. We also don't have an assigned maintainer for the fork. I'm also unsure of how @Jwhiles feels about the fork?

My understanding is that the main change is the change from Qunit to tape for testing.

### PR DESCRIPTION
**Pull request by astroash**
Duplicated pure-functions-easy-testing so that it is no longer a fork off of @Jwhiles repo.

fixes #759 :cactus:

### CODE REVIEW

**Comment by Jwhiles** [comment]
Excellent work. Love it. :fire: :+1: :godmode:

**Comment by astroash** [comment]
@Jwhiles how did i not know that `:godmode:` was an emoji ⚡️  :godmode: ⚡️ :godmode: ⚡️

**Comment by Jwhiles** [comment]
@astroash :hurtrealbad:

**Comment by Jwhiles** [comment]
collect them all  :feelsgood: | :finnadie: | :goberserk: | :godmode: | :hurtrealbad: | :rage1: | :rage2: | :rage3: | :rage4: | :suspect:

**Pull request merged**
