### PR TITLE
inform students about in-app github notifications within scavenger hunt doc

### LINKED ISSUE #420: point students to in-app notification system
Most of FAC9 seem to have discovered this after the course.
We pointed FAC10 & FAC11 to it verbally

**As a** student on the course
**I want to** learn how to use [github's in-app notification system](https://github.com/notifications) (rather than emails?)
**So that** I am not spammed with so many notifications that I miss updates to repos other than the one I'm currently working on (e.g. friends' repos, `london-programme`, `master-reference`, etc)  
&  
**so that** I can learn how to use github to stay across multiple repos as a project manager  
&  
**so that** I have a better appreciation of how my use of github effects members of my team _other than just the developers_  
&  
**so that** I am more likely to watch & star repos, because I'm scared of being overwhelmed by the notifications

image
image
etc.

### PR DESCRIPTION
**Pull request by jsms90**
Just adds one line & a pic to let students know about in-app notifications

relates #420

### CODE REVIEW

**Comment by mattlub** [comment]
@jsms90 
> tell students to "watch" international, <city>-programme & master-reference

imo this is not a good idea on the first day as it is likely to leave new students with an endless list of notifications, potentially drowing out ones they will likely be more interested in i.e. related to their projects

**Comment by jsms90** [comment]
@m4v15  good point!

I just want to make sure that they're notified whenever we tag them in a `master-reference` or `nazareth-programme` issue or assign them. But they don't need to watch the repo for that :+1:

**Comment by mattlub** [comment]
@jsms90 yep, definitely agree they should be shown to turn on online notifications.

**Comment by eliascodes** [comment]
@jsms90 can we remove "**London's** Github Scavenger Hunt" from the document heading please?

**Comment by jsms90** [comment]
@eliascodes it's already been taken out via another PR. Merging this shouldn't put the title back in. But I can pull the current master, merge and push to this branch for clarity, as soon as I get back to my computer?

**Comment by eliascodes** [comment]
@jsms90 OK, no that's fine.

**Comment by jsms90** [comment]
@sofer second approval. please merge :tada:

**Pull request merged**
