### PR TITLE
Add another error handling workshop link to readme

### PR DESCRIPTION
**Pull request by Jwhiles**

### CODE REVIEW

**Comment by jsms90** [comment]
@Jwhiles @njsfield Which one is being used?

**Comment by njsfield** [comment]
As [the other workshop](https://github.com/njsfield/error-handling-workshop) was reviewed and merged yesterday and has just been taught in Nazareth, that one should be used to avoid confusion. @Jwhiles perhaps close the PR and make a separate PR in the resources?

**Comment by jsms90** [comment]
It's a real shame that there wasn't a combined effort to make one workshop :disappointed: , because you guys have included fairly different things, and there's so much value in both!! It seems like a lot of effort has gone in to both workshops. They're both very good, and I would love for FAC10 to benefit from the best in each one.

@Jwhiles Considering FAC9 (and now FAC10) have requested in s-g-c that mentors ensure that the coursebook is always up-to-date, I'm hesitant for us to put two workshops into this time slot in the docs, when there is only time for them to complete one of them. And it's unfortunate that this PR has been raised after the first day of this week has already begun (in Nazareth).

@njsfield Although it is very helpful from the perspective of making iterative improvements, to have a wider base of people providing feedback about the same material, I don't necessarily think that London and Nazareth absolutely _have_ to deliver the same material.

For example, given that they are 1 day ahead of us, if Nazareth provides feedback that could improve things for London, it would be foolish for us _not_ to change the material accordingly. In a slightly more drastic example, Nazareth's week 2 project was a to-do list app instead of a stopwatch (based on the difference in experience prior to the course, as far as I know...?) It's important for us not to get so bogged down in rules, that we don't meet the needs of our students as best as we possibly can.

I appreciate that there is very little time now, but it would be wonderful if you could both combine your efforts? My suggestion would be:
+ @Jwhiles fork the workshop that is already in the master reference: https://github.com/njsfield/error-handling-workshop
+ add pieces from the second workshop, wherever this helps / makes sense
+ submit a PR for @njsfield 's review and approval

If there is not enough time for either/both of you to manage this before tomorrow morning, it might be best to follow Nick's suggestion, and put John's in `resources`? This isn't ideal - much better to deliver the best of both to our students, but having two competing workshops seems more problematic.

**Comment by bradreeder** [comment]
I agree with @jsms90 's suggestion if you find the time @Jwhiles , thanks for taking the time to prepare this. Otherwise I've added a link to this to the archive in #43 for the review of FAC10 when next curriculum-planning swings around. 

This PR has been open for 2 weeks and week 5 has already been delivered. Closed.

**Pull request closed without merging**
