### PR TITLE
Week 6 schedule

### PR DESCRIPTION
**Pull request by shiryz**
Adds a link to the morning challenge.

### CODE REVIEW

**Comment by emilyb7** [comment]
Nice @shiryz ! I've only had a quick look at the challenge, I will try it out later 👍

**Comment by emilyb7** [comment]
@shiryz should we maybe be merging into the week-6 branch instead of straight into master?

**Comment by shiryz** [comment]
@emilyb7, yes that's a good idea.

**Comment by emilyb7** [comment]
@shiryz i've merged this into the week 6 branch, and made a pull request to master that includes the whole schedule + projects! (hope that's all ok)

**Pull request closed without merging**
