### PR TITLE
Expanding on the 'why' of each research topic

### PR DESCRIPTION
**Pull request by teenie-quaggard**
This is to try to get students to think more critically of how this might be useful to them.

### CODE REVIEW

**Comment by oliverjam** [comment]
I like the changes 👍 

Not related to those, but how useful is the final topic? Won't they already have done the updated request morning challenge at this point? Are we expecting them to find and use something like `node-fetch` or `isomorphic-fetch`, or just use the (deprecated) `request` module?

**Comment by teenie-quaggard** [comment]
> Not related to those, but how useful is the final topic? Won't they already have done the updated request morning challenge at this point? Are we expecting them to find and use something like node-fetch or isomorphic-fetch, or just use the (deprecated) request module?

True...I think it was just to get them to understand that there are ways that API calls have been abstracted and to experience searching for alternatives. Do you think we should maybe change it to be more specific? Maybe practice using something like [Axios](https://www.npmjs.com/package/axios) which I think they use pretty extensively at the sister campuses in the Middle East

**Comment by oliverjam** [comment]
Will they have covered `fetch`/promises at this point? I think I'd rather they get more practice using a similar API to the browser rather than get confused with something fairly different (like Axios)

**Comment by teenie-quaggard** [comment]
@oliverjam I think they don't 'officially' learn ```fetch``` until week 8! But I know that @astroash was planning on a big restructuring of the curriculum, so maybe it's best if we leave this until we've all agreed on the changes. I'll open up an issue on this!

Thanks for all your input! It's been super helpful 🧠

**Comment by oliverjam** [comment]
I think we might need to fix this, since I assume if they haven't covered promises yet they'll be confused by any request library they discover during research

**Comment by teenie-quaggard** [comment]
Could we move the week 8 research topic here, or is it too soon? We could then switch to researching alternatives (such as Axios) to week 8.

> Promises and Fetch

    What is a Promise?
    What is fetch and how do you use it?
    What advantages do promises provide over callbacks, what are the downsides of using promises?
    What are the downsides to using Fetch? i.e. what does fetch not do for you?

**Comment by oliverjam** [comment]
I think promises are too important to leave to a research topic. I just asked @starsuit about this and she didn't even remember server-side HTTP requests being a research topic 🙃

Also it'd be a bit weird to research `fetch` in a node week

**Comment by starsuit** [comment]
>I think promises are too important to leave to a research topic

There's a workshop on promises in week 7, I actually thought it a bit odd that promises were a research afternoon **and** a workshop

**Pull request merged**
