### PR TITLE
Add cohort code of conduct

### PR DESCRIPTION
**Pull request by arrested-developer**
Relates > #929

### CODE REVIEW

**Comment by m4v15** [comment]
I think this looks good, tagging @ibraghada to have Gaza Eyes on it

**Comment by astroash** [comment]
I think this activity is a great idea. I just wonder if 1 hr 20 is enough time for all the activities mentioned? Is there any other give in the timetable for this week _cough_ scavenger hunt _cough_

**Comment by arrested-developer** [comment]
@astroash I'm in favour of scrapping the scavenger hunt 😴. But the repos still need signposting, no?

**Comment by astroash** [comment]
@arrested-developer yeah a walkthrough of the fac org is needed, but could take less time, then students can be pointed to the scavenger hunt if they want to do it in their own time? There's always keen beans in the first week. 

How about keeping this slot for creating the cohort code of conduct, moving everything else to the scavenger hunt slot, then using any spare time for the consensus based decision making?

Also side note, is the "consensus based decision making" activity still run as a facilitated discussion? And is it relevant to all campuses? I know Gaza do not run this, does Naz @shiryz?

Either way, how about something like:

## Day 1

- 10.00 - 10.30 — Welcome talk
- 10:30 - 11:30 — Name game with as many members of Founders and Coders as possible!
- 11:30 - 11:40 - Toilet/Coffee Break
- 11:40 - 13:00 - Code of Conduct
  - [Organisation wide Code of Conduct](https://github.com/foundersandcoders/master-reference/blob/master/code-of-conduct.md)
  - Students create their own [Cohort Code of Conduct](cohort-code-of-conduct.md)

— LUNCH —

- 14.00 - 15.00 - Course overview
  - Go through 16 week [schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook)
  - [House rules](../general/house-rules.md)
  - Campus-specific info
  - Introduce FAC organisation on github and key repos (`campus-programme && master-reference`)
  - Introduce gitter channels
- 15:00 - 15:50 — Introduction to [Pair Programming](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/pair-programming.md)
- 15:50 - 16:00 — Toilet/Coffee Break
- 16:00 - 17:00 — [Accessibility Workshop](https://github.com/foundersandcoders/web-accessibility/blob/master/putting-yourself-in-someone-elses-shoes.md)
- 17:00 - 18:00 — Introduction to consensus based decision-making

**Comment by arrested-developer** [comment]
What do Gaza and Al-Khalil do instead of consensus? Should we add an option here?

@m4v15 @ibraghada

**Comment by m4v15** [comment]
The day always over runs due to a multitude of introductory talks etc. so nothing replaces it.

**Comment by rebeccaradding** [comment]
I'd suggest dropping the consensus decision making session as we're about to propose a shift in member engagement/decision-making for the May AGM. Agreed about the scavenger hunt, it's a relic of another era...

**Comment by m4v15** [comment]
raised an issue so we can continue this discussion here: https://github.com/foundersandcoders/master-reference/issues/931

So this can probably be merged?

**Comment by astroash** [comment]
@m4v15 do you have any concerns with the above suggestions? Seems like dropping scavenger hunt and consensus decision making can be actioned in this PR.

**Comment by arrested-developer** [comment]
I'm starting to think it might be nice to rename this the "cohort charter" rather than "cohort code of conduct" to differentiate it more from the org-wide code of conduct

**Comment by m4v15** [comment]
> @m4v15 do you have any concerns with the above suggestions? Seems like dropping scavenger hunt and consensus decision making can be actioned in this PR.

I don't really have any concerns and it's probably the right thing to do but I think there's more changes that could be made to that first schedule and we could thrash out what they are in the issue I linked to.

As it is, this PR already does what it sets out to do, we can just merge it in then open another one for re-ordering the schedule of the day (not sure what is gained from doing it in this PR)

**Comment by astroash** [comment]
My main issue is that the timings in this PR do not work. 

Although, as long as this is changed before the next cohort it doesn’t matter if it is addressed in this PR or a subsequent one.

**Comment by m4v15** [comment]
@astroash I was assuming the timings went OK for FAC15 and this is just reflecting that. 

wrt scavenger hunt droppage, I probably agree a think it could be done, but think we should think about what gets lost if it's dropped and whether just telling them about the repo's _is_ an adequate replacement. Like it probably is and it's fine, but I just think we can take the discussion the issue and merge this in.

@eliascodes @shiryz You guy's decide, do we:

- Update this PR to drop Scavenger Hunt & Consensus based decision making
- Merge this PR, Scavenger Hunt and CBDM to be addressed in the future

If the former, someone do it and get this merged please.

**Comment by eliascodes** [comment]
Merging b/c of foundersandcoders/london-programme#882

**Pull request merged**
