### PR TITLE
WORK IN PROGRESS: First pass at curriculum

### PR DESCRIPTION
**Pull request by des-des**
Can everyone who sees this hold of commenting until me and brad are happy with the first draft. We'll open out the discussion on this pull + elsewhere when we have cleaned this up a bit.

@bradreeder So I copied the notes from yesterday into md.
#1

This is mostly a reflection of me and brad's feelings of how the course should be structured, we definitely need more options on this.. Once me and brad are happy with this pull, we will open up a wider debate around it. We will also need to work with FAC9 to get this into its final form. Me and brad have made some changes from their current curriculum, some of them based on feedback we have had in the last 5 weeks..

There also needs to be a wider discussion about how having this master curriculum document will play with the idea that FAC x-1 create the next curriculum. I feel it is about striking a balance between being able to use the sum of lessons learned in all prev facs vs giving the current cohort control..

### CODE REVIEW

**Comment by sohilpandya** [comment]
Great start @des-des, are we having a meeting with regards to this? I've probably got some feedback with regards to the initial curriculum you've put in place. Are you in FAC today?

**Comment by des-des** [comment]
@sohilpandya I think post your feedback on this pull, so that everybody can see. But ill be in fac today / tomoz if you wanna chat.

**Comment by des-des** [comment]
@sohilpandya also have updated pr description, hold of till we think it is in discussion worthy form

**Comment by iteles** [comment]
@des-des It's worth filling out the detail in the issue with *why* this is being done. As far as I understand from our conversations, this first pass is being put together based on what we have taught in the past (essentially bringing together what has worked well in past curriculums) as a **starting point** for the wider discussion that will happen.

**Comment by bradreeder** [comment]
@iteles Absolutely, it's just to get the ball rolling. We're putting this draft together to encompass recent gitbooks, FAC9 feedback so far, and some of our own input. The intention is that once we have a first draft it can be used as a point of discussion to tear apart and refactor as a group. We can then use the refactored version with FAC9 when we do curriculum planning and get their feedback.

**Comment by bradreeder** [comment]
@sofer I wouldn't underestimate how much time planning can take. I think I will raise a business issue with what I have in mind as I think this subject warrants its own discussion.

**Comment by des-des** [comment]
@bradreeder okay I think we can merge this down to master.

I have read back through the notes from the meeting
https://hackpad.com/Master-Ref-meeting-mon-5th-Dec-UrrMDTohONE

Most of them were not directly applicable to the curriculum draft, so when I have time I will go back through and raise a bunch of issues

**Comment by bradreeder** [comment]
I've read through and I'm happy to open this up for the next round of review. I will merge this then create an issue for others to be directed to to give their feedback.

**Comment by des-des** [comment]
issue here: https://github.com/foundersandcoders/master-reference/issues

**Pull request merged**
