### PR TITLE
Changed link to coverage to 'learn tape'

### PR DESCRIPTION
**Pull request by zurda**
Relates to  #965

### CODE REVIEW

**Comment by shiryz** [comment]
A bit late to the party, but the learn-tape guide is outdated, it still uses Istanbul (deprecated :disappointed:) and it overlaps with the later code along.
It doesn't add a lot of knowledge on tape since students would've already done it in the intro and fizzbuzz ws.

**Comment by astroash** [comment]
@shiryz do you think this resource should be removed all together?

**Comment by shiryz** [comment]
@astroash, it should either be moved to be done after the roman numerals code along or updated to match the fizzbuzz one.

**Comment by oliverjam** [comment]
I think Learn Tape was only linked as a bonus for students to take a look at if they happened to be finished early before lunch. Maybe it would be better to write up a bonus section for the fizzbuzz workshop to act as a stretch goal so we can drop Learn Tape entirely.

**Comment by shiryz** [comment]
@oliverjam 

> Maybe it would be better to write up a bonus section for the fizzbuzz workshop

Yes, we should :sparkles: :heart_eyes: 

Most of the students in FACN5 finished this really early, so this would have been really useful if it were in line with what they've just learned

**Pull request merged**
