### PR TITLE
Add morning challenge for week 4 day 3

### PR DESCRIPTION
**Pull request by stevehopkinson**
It's about modularisation. #30

### CODE REVIEW

**Comment by des-des** [comment]
image

**Comment by des-des** [comment]
@stevehopkinson also, see the contributing file, commit messages need to have issue numbers, and the pull needs to have a description

**Comment by jsms90** [comment]
@stevehopkinson Could you update the [week 4 readme file](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-4/README.md) please, with a link to this morning challenge, instead of saying
> **to be created**

with a direct link to dan's repo?

**Comment by stevehopkinson** [comment]
Readme updated.

**Comment by jsms90** [comment]
@stevehopkinson 
Thanks! But this is still gonna stop your PR getting merged:
> @stevehopkinson also, see the contributing file, commit messages need to have issue numbers, and the pull needs to have a description

**Comment by stevehopkinson** [comment]
Done.

**Pull request merged**
