### PR TITLE
adds basic project outline for hapi-views (need links) 

### PR DESCRIPTION
**Pull request by SavageWilliam**
concerns: #33 

@marisid After you have completed the learning outcomes, you might want to add points under the 'Goals' section for completeness. 

@msachi @jsms90 @denesnori @lucymonie  - I currently have the use of cookies in the project as a 'stretch goal', as it was the 'floater' topic between weeks. Are we happy with this decision? or should it be bumped up in priority? 

Hapi-views will be the first week where the students have the option to create login functionality (database week aren't introducing this). Shall we tailor the Wednesday morning cookie ws around a full login flow with database data and cookies?

### CODE REVIEW

**Comment by msachi** [comment]
@SavageWilliam I would say that we should make cookies one of the main goals. It will be their only opportunity to implement authentication that is _not_ third-party (i.e. not OAuth). However, it is already quite a big project as it is, so I think it would be a good idea (as you suggest) to show them pretty much exactly how this is done in the workshop, rather than letting them spend all their project time on getting cookies to work.

If we decide to make cookies optional, then I don't think we should have a cookie workshop on Weds (which should be reserved for topics of high relevance to the projects), but instead include it as one of the README topics.

**Comment by msachi** [comment]
Also, did we not want to make this a 'news feed' project? I think the consensus in our cohort was that some of the project instructions were too open-ended, so it might be a good idea to be more specific. We could give them an open-ended and a more specific option, as was done for our database week.

**Comment by marisid** [comment]
@msachi I think that the news feed project was suggested for week 5 (see comment [here](https://github.com/foundersandcoders/master-reference/issues/31#issuecomment-271303283)). Building a blog site is a good idea and perfect for building a CMS using handlebars. Maybe more on the open-ended side but I think everyone knows what a blog site is and they can be creative and can take it to whichever direction they want.

@SavageWilliam I made some small edits to the project file - hope that's ok. And I agree that if we have a workshop on Wed morning, we should make the use of cookies a primary goal (maybe move it in the readme under
>What's also important

**Comment by msachi** [comment]
@marisid Agreed 👍

**Comment by bradreeder** [comment]
@SavageWilliam @msachi @marisid is this ready for review? Please assign to me or @des-des when your PRs are ready.

**Comment by msachi** [comment]
@SavageWilliam Do you want to change the cookie bit?

@bradreeder Are we supposed to have PRs reviewed when merging any branch or just when merging to master?

**Comment by bradreeder** [comment]
@msachi Just to master. I think Eoin mistook one of the prior merges for a merge into master.

**Comment by des-des** [comment]
Merging all your branches together for one big review is not helpful. Lots of small pulls into master is better!

**Comment by bradreeder** [comment]
@des-des that's possibly my bad as I may have advised that during planning while I was working out the best way to manage this. My bad.

**Comment by SavageWilliam** [comment]
@msachi @marisid Im happy to make cookie use a requirement of the project, will amend the project description now! And create the ws this week! 

@des-des I can change the base of this PR to the master if you like?

**Comment by des-des** [comment]
@SavageWilliam Make a pull request from https://github.com/foundersandcoders/master-reference/tree/week-7-hapi-views into master.

Assign this to me once this branch is ready to go and *and* any branches it is dependent on have gone into master.

**Comment by des-des** [comment]
@SavageWilliam Also, pls assign me to pull requests.

**Comment by marisid** [comment]
Looks good @SavageWilliam - I'm merging! So, now we are ready to make a PR from our main branch to master, right? :fireworks: I'm doing this now.

**Comment by des-des** [comment]
@marisid pls read my comment above

**Comment by marisid** [comment]
@des-des so far we've had conflicting instructions as to how we manage our branches. I thought that we make branches off our branch for a specific week and then into master (as summarised [here](https://github.com/foundersandcoders/master-reference/issues/33#issuecomment-274060586) in our planning phase). This was our last "secondary" branch for week 7 that was opened quite some time ago. Wouldn't it make sense to change the style we manage our branches in the next round of PRs? I think @bradreeder has already poointed out this discrepancy. Sorry - from now on **all** branches will pass from you when trying to merge into master.

**Comment by msachi** [comment]
I agree with @marisid, we were told to only assign you when merging to master (which was supposed to be the final step), not for any 'secondary' branch merging. I think it's confusing to be changing the workflow half-way through the process. Also, wouldn't secondary branches still be useful, so that if several of us are working on the same document we can do so without conflicts?

**Comment by des-des** [comment]
@bradreeder What is the process here? Small pull requests into master make for a much better QA process.

Big pull requests are bad, which is why I have already said we should not be merging lots of branches together to make one big pr for QA :cry:

Can we get some clarity?

**Pull request merged**
