### PR TITLE
clarify(?) wk13+ content

### LINKED ISSUE #387: Curriculum Overview.md - schedule not obvious past reading week
Page in question: master-reference/coursebook/general/curriculum-overview.md

It is not obvious from the Curriculum Overview.md what is being taught past reading week. It is mentioned briefly at the top of the page in **Outline**, however it is not mentioned in the detailed **Overview**. If you are scrolling through the page then it appears the course finishes on week 8.

### PR DESCRIPTION
**Pull request by eliascodes**
fixes #387 (probably)

### CODE REVIEW

**Comment by astroash** [comment]
If LOs from #692 get finalised it could be great to have those linked here too...

**Comment by astroash** [comment]
Also, I love how I was complaining about mazref in my first week... Although that issue was resolved in #530

**Comment by eliascodes** [comment]
Cool, closing this then as unnecessary. Also weeks 13+ covered in `self-organising.md`.

**Comment by astroash** [comment]
IMO I wouldn't close this, I think it's still useful to add in (even if it doesn't relate to my issue).

**Pull request closed without merging**
